services:
  - type: web
    name: baitapweb
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_TO
        sync: false
